### ISSUE TITLE
PHP 7.1 compatibility

### ISSUE THREAD

**Issue by slaFFik** [slaFFik/BP-Groups-Extras#116]
https://wordpress.org/support/topic/illegal-string-offset-gpages/

> PHP Warning:  Illegal string offset 'gpages' in /site_path/wp-content/plugins/buddypress-groups-extras/core/loader.php on line 123
PHP Warning:  Illegal string offset 'gpages' in /site_path/wp-content/plugins/buddypress-groups-extras/core/loader.php on line 130

**Comment by AiratHalitov** [comment]
New warnings in log:

```
PHP Warning:  Illegal string offset 'display_page_layout' in /site_path/wp-content/plugins/buddypress-groups-extras/core/loader.php on line 80
PHP Warning:  Illegal string offset 'gpage_id' in /site_path/wp-content/plugins/buddypress-groups-extras/core/loader.php on line 1079
PHP Warning:  Illegal string offset 'gpage_id' in /site_path/wp-content/plugins/buddypress-groups-extras/core/loader.php on line 1092
```
