### ISSUE TITLE
Unable to click and drag

### ISSUE THREAD

**Issue by kalico1** [slaFFik/BP-Groups-Extras#121]
On the "Extras" tab, I'm unable to click and drag in the section to rearrange menu items.  I have the latest version installed. There are no errors in the console. Could this be a problem with CSS? I can provide access if needed.

**Comment by kalico1** [comment]
Additional problem: when I go to Extras tab >> All Fields, select one of my pre-sets and click on "Import" the fields are not added. Beginning to think something is wonky with my CSS, but I'm not sure what to look for.

**Comment by slaFFik** [comment]
Drag-n-drop: I will check. Thanks for the report. But I'm pretty sure that this is the issue with the current theme or plugin. Please try on a clean install with 2015 theme and BuddyPress and BPGE active plugins only.

I've created a separated issue #122 for your second request.

**Comment by kalico1** [comment]
Yes, I agree. It's very likely the theme. Can you give me any ideas of what to check? ie, what would cause this to happen? I've looked at the CSS and the console, but I'm not seeing anything useful. 

I've been using a child theme of Zerif Pro since the start of this project, but they recently offered an update, which caused a lot of issues (and I had used a child theme to avoid this!). I am not sure where to begin troubleshooting. This is a professional/client site, and it's live, so I can't make changes that will affect how it looks. Any assistance would be most appreciated.

**Comment by kalico1** [comment]
I've done some further testing, and I suspect this is at least in part related to the theme. I reported the issue to ThemeIsle, and I'll let you know what I hear back.

**Comment by kalico1** [comment]
I'm doing a massive plugin and theme conflict test across my entire site. As a result, this issue is almost resolved. I've de-escalated it from "freaking panic" to "annoyance".

At this point, the functionality "works" (i.e., it _does_ reorder the pages), but there is a weird "ghosting" problem with everything I click and drag.

I've created a [screencast](https://screencast.com/t/lFWsHbkoNj1) of the problem as it appears on Chrome 58.0.3029.110 / Mac 10.12.4. 

The screencast demonstrates how it looks with the CSS from my child theme turned on. Gist of child theme CSS is [here](https://gist.github.com/kalico1/bd7e036d83cbc068f2862022b88d06c8).

When I remove my child theme CSS and go with JUST the parent theme CSS, the ghosting goes away. It would be great to figure out what's causing this.

**Comment by kalico1** [comment]
Problem solved! See #122
