### ISSUE TITLE
Warning: Illegal string offset ‘gpages’ in core/loader.php on line 123

### ISSUE THREAD

**Issue by slaFFik** [slaFFik/BP-Groups-Extras#123]
https://wordpress.org/support/topic/error-after-migrating-host/

After migrating host (changing domain or path is changed?)

**Comment by philosofree** [comment]
I am trying to use the plugin, but having no luck at all.
I follow the tutorial and when I open the test group that has the feature for GP-groups-extra, it crashes with Warning: Illegal string offset 'gpage_id' in /home/philchen/public_html/lisn/wp-content/plugins/buddypress-groups-extras/core/loader.php on line 1079

Warning: Illegal string offset 'display_page_layout' in /home/philchen/public_html/lisn/wp-content/plugins/buddypress-groups-extras/core/loader.php on line 80

Can you advise what to do, or if there is a solution or alternative?
thanks
Phil

**Comment by slaFFik** [comment]
Make sure that 
1. you have the latest version of the BPGE plugin activated.
2. you saved options in the group Admin -> Extras -> General page.

I will investigate the issue anyway.
