### ISSUE TITLE
Spelling Issues

### ISSUE THREAD

**Issue by garrett-eclipse** [slaFFik/BP-Groups-Extras#127]
Hello,

Just creating this ticket to submit a PR with spelling fixes. Full list below;

1. Spelling - succefully should be successfully
Permalink - https://translate.wordpress.org/projects/wp-plugins/buddypress-groups-extras/stable/en-ca/default?filters%5Boriginal_id%5D=3103612

2. Spelling - realease should be release
Permalink - https://translate.wordpress.org/projects/wp-plugins/buddypress-groups-extras/dev-readme/en-ca/default?filters%5Boriginal_id%5D=2592139

3. Spelling - submin should be submit
Permalink - https://translate.wordpress.org/projects/wp-plugins/buddypress-groups-extras/dev-readme/en-ca/default?filters%5Boriginal_id%5D=2592103

4. Spelling - inherites should be inherit
Permalink - https://translate.wordpress.org/projects/wp-plugins/buddypress-groups-extras/dev-readme/en-ca/default?filters%5Boriginal_id%5D=2592088

Cheers

**Comment by slaFFik** [comment]
Oh, thank you!

**Comment by slaFFik** [comment]
PR merged, closing this ticket.

Feel free to open issues/PR for any other fixes that you find. Thank you for improving this plugin.

**Comment by garrett-eclipse** [comment]
No worries mate, if I come across anything else would be happy to provide fixes. All the best
