### ISSUE TITLE
PHP Warning:  Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by nevvkid** [slaFFik/BP-Groups-Extras#62]
Hi there. I get alot of these errors below in my installation using wordpress 4.2.2 and BP-Groups-Extras version 3.6.7.2. Can i do something about this? 

Thx.

> [Mon Jun 15 11:10:02.904363 2015] [fcgid:warn] [pid 5366] [client 91.66.248.222:51317] mod_fcgid: stderr: PHP Warning:  Cannot use a scalar value as an array in /var/www/vhosts/mydomain.de/httpdocs/wp-content/plugins/buddypress-groups-extras/core/loader.php on line 89, referer: http://www.mydomain.de/groups/testgruppe3/
[Mon Jun 15 11:10:03.138664 2015] [fcgid:warn] [pid 5366] [client 91.66.248.222:51317] mod_fcgid: stderr: PHP Warning:  Cannot use a scalar value as an array in /var/www/vhosts/mydomain.de/httpdocs/wp-content/plugins/buddypress-groups-extras/core/loader.php on line 89, referer: http://www.mydomain.de/groups/testgruppe3/

**Comment by slaFFik** [comment]
Just for the reference: https://github.com/slaFFik/BP-Groups-Extras/blob/master/core/loader.php#L89

**Comment by slaFFik** [comment]
I'm a bit surprised. I will need to check this. Thanks for reporting.

**Comment by slaFFik** [comment]
Should be fixed now, although I was not able to replicate this.
