### ISSUE TITLE
Redirect after Saving Page etc

### ISSUE THREAD

**Issue by slaFFik** [slaFFik/BP-Groups-Extras#64]
See this thread for details: https://wordpress.org/support/topic/redirect-after-saving-page?replies=4#post-8201191

**Comment by tammy1999** [comment]
Will you be putting a solution to the problem here?

**Comment by slaFFik** [comment]
This issue here will be closed once it will be fixed. Shortly after that the new version will be deployed to WordPress.org.
No ETA right now.

**Comment by slaFFik** [comment]
#99

**Comment by slaFFik** [comment]
This redirect to admin area is caused definitely not by a BPGE plugin. Seems somethings else is doing that redirect.
