### ISSUE TITLE
Plugin Conflict with BP_Groups_Hierarchy

### ISSUE THREAD

**Issue by slaFFik** [slaFFik/BP-Groups-Extras#67]
Details: https://wordpress.org/support/topic/plugin-conflict-with-bp_groups_hierarchy?replies=1

https://en-ca.wordpress.org/plugins/bp-group-hierarchy/

**Comment by garrett-eclipse** [comment]
Hey Slava,

I believe I have a fix for this.

Following this reply on WP Forums on a related topic;
https://wordpress.org/support/topic/notice-indirect-modification-of-overloaded-property-wp_object_cachecache?replies=14#post-6468640

I found if you replace the follow line (68) of core/loader.php;
`$bp->groups->current_group->extras['display_page_layout'] = 'profile';`
With these lines of code;
```
$current_group_extras = $bp->groups->current_group->extras;
$current_group_extras['display_page_layout'] = 'profile';
$bp->groups->current_group->extras = $current_group_extras;
```

The issue goes away. May need to go through the plugin to check all setting of extra attributes when referring to the current_group, just to be safe.

Note: This fix does work for sites with and without the Hierarchy plugin. But if you want you can do a conditional check if that plugin is active and switch the approach. Although no real benefit.
