### ISSUE TITLE
WP 4.5.3 and BP 2.6 compatibility issue

### ISSUE THREAD

**Issue by fritzgy** [slaFFik/BP-Groups-Extras#94]
The "reorder here all navigation links in this group" and "Rename the Home group page" functions are not working.

**Comment by slaFFik** [comment]
https://buddypress.org/support/topic/bp-2-6-and-buddypress-group-extras-plugin/#post-256560

https://buddypress.org/support/topic/redirect-to-another-page-and-not-staying-on-the-right-page/
